library(Hmisc)
 t<-read.table("/home/nz2274/Projects/PSAP_calibrate/test/test.genes.cadd1.txt.hg19_multianno.txt",header=1,comment.char="",sep="\t")
pdf("/home/nz2274/Projects/PSAP_calibrate/test/cadd_vs.pdf")
plot(t$CADD13_PHRED,t$CADD_Phred)
abline(0,1)
text(50,50,rcorr(t[,c("CADD13_PHRED","CADD_Phred")]))
plot(t$CADD14_Phred,t$CADD_Phred)
abline(0,1)
text(50,50,rcorr(t[,c("CADD14_Phred","CADD_Phred")]))

plot(t$CADD13_PHRED,t$CADD14_Phred)
abline(0,1)
text(50,50,rcorr(t[,c("CADD13_PHRED","CADD14_Phred")]))
#rcorr(x, type="pearson") 
dev.off()
